version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    groups:
      nestjs:
        applies-to: security-updates
        patterns:
          - "@nestjs/*"
      prisma:
        applies-to: security-updates
        patterns:
          - "@prisma/*"
          - "prisma"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    groups:
      nextjs:
        applies-to: security-updates
        patterns:
          - "next"
          - "react"
          - "react-dom"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 0
