export enum ProfileMediaUploadPurpose {
  CANDIDATE_AVATAR = 'CANDIDATE_AVATAR',
  CANDIDATE_RESUME = 'CANDIDATE_RESUME',
  APPLICATION_STAGE_FILE = 'APPLICATION_STAGE_FILE',
  B2B_USER_AVATAR = 'B2B_USER_AVATAR',
  TENANT_LOGO = 'TENANT_LOGO',
  TENANT_BANNER = 'TENANT_BANNER',
}
